# Uygulama adı
spring.application.name=DejaView

# Geliştirme profilinde çalışacak ayarlar
spring.profiles.active=dev
server.port=8080

# Canlı ortam ayarları
# spring.profiles.active=prod
# server.port=443
# --- H2 Veritabanı Ayarları ---
spring.datasource.url=jdbc:h2:mem:dejaviewdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Konfigürasyonu
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Konsol Ayarları (Tarayıcıdan izleyebilmek için)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# --- Elasticsearch Ayarları ---
spring.elasticsearch.uris=http://192.168.1.50:9200
spring.elasticsearch.rest.uris=http://192.168.1.50:9200

# ElasticsearchConfig içindeki username ve password placeholder hatalarını çözmek için eklenen alanlar
spring.elasticsearch.rest.username=
spring.elasticsearch.rest.password=
spring.elasticsearch.username=
spring.elasticsearch.password=

spring.main.allow-bean-definition-overriding=true

# --- OpenAI API Anahtarı ---
openai.api.key=sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# --- Gemini API ---
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.key=${GEMINI_API_KEY:}


# Swagger UI erişim adresi konfigürasyonu
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
